path.n: NAMESPACE
path.d: DESCRIPTION
dir.r: R
dir.v: vignettes
dir.t: tests
extra.suggests:
  - ggplot2
  - curl
pkg_ignore:
  - tidyverse
  - leaflet
  - reactable
  - crosstalk
  - tidyr
  - htmltools
  - arcgeocoder
  - tidygeocoder
document: yes
normalize: yes
inside_rmd: yes
must.exist: yes
check_if_suggests_is_installed: yes
